/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{sellerId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get metadata from the root of the API */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        /** @description Information about a new pet in the system */
        requestBody?: {
            content: {
                "multipart/form-data": {
                    planId?: number;
                    customerId?: number;
                    /** @enum {unknown} */
                    paymentMethodId?: "CREDIT_CARD" | "BANK_TEANSFER";
                };
            };
        };
        responses: {
            /** @description 注文処理を行うAPI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 不正なリクエスト
             *      */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
